parameters:
    protheus:
        ftp:
            host: "ftpdtc.totvs.com.br"
            port: 21
            timeout: 90
            user: "nrs3vm_prd@datacenter.local"
            pass: "Ft#3s@17dt"
            ambi: "NRS3VM_PRD"
        webservices:
            V_PROT_FIN_VOGEL:
                wsdl: "http://187.94.63.55:14801/ws/V_PROT_FIN_VOGEL.apw?WSDL"
                methods:
                    BUSCAFORNECEDOR: BUSCAFORNECEDOR
                    BUSCAPA: BUSCAPA
                    GERANFFATURA: GERANFFATURA
                    INCLUIPA: INCLUIPA
                    NOVOBOLETO: NOVOBOLETO
services:
    integracao_protheus:
          alias: App\Services\IntegracaoProtheus
          public: true

    App\Services\IntegracaoProtheus:
          public: false
          arguments: ["@doctrine", "@logger", "@integracao_circuito_protheus", "%protheus%"]
          tags:
              - { name: monolog.logger, channel: protheus }

    integracao_circuito_protheus:
          alias: App\Services\IntegracaoProtheus\Circuito\IntegrarCircuito
          public: true

    App\Services\IntegracaoProtheus\Circuito\IntegrarCircuito:
          public: false
          arguments: ["@doctrine", "@logger", "%protheus%"]
          tags:
              - { name: monolog.logger, channel: protheus }
