parameters:
    salesforce:
        base: 'https://vogeltelecom--uat.my.salesforce.com'
        oauth:
            authorize: 'https://test.salesforce.com/services/oauth2/authorize'
            token: 'https://test.salesforce.com/services/oauth2/token'
            revoke: 'https://test.salesforce.com/services/oauth2/revoke'
            redirect_uri: https://apis.dev.vogeltelecom.com
            auth:
                grant_type: 'password'
                client_id: '3MVG9U_dUptXGpYLfWWXIlYB2gaLSuV22vX1WBF6bZx8SDTmLKlUUa4sTwUryTZW80hNoaf0RBnPXseSJHgOP'
                client_secret: '814C48B5097DAD1B9902D765247883500B54034DCEF1DBB17D503DBFB5087A0A'
                username: 'sistemas@vogeltelecom.com.uat'
                password: 'Vogel#telecom27H2B2SsgBXxvtCfMmVRx0n18'
        account:
            url: /services/data/v39.0/sobjects/Account
        circuito:
            url: /services/data/v39.0/sobjects/Circuito__c
        endereco:
            url: /services/data/v39.0/sobjects/Endereco__c
        cidade:
            url: /services/data/v39.0/sobjects/Cidade__c
        circuito_atributo:
            url: /services/data/v39.0/sobjects/CircuitoAtributo__c

            