parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver:   '%env(resolve:DB_DRIVER)%'
                host:     '%env(resolve:DB_HOST)%'
                port:     '%env(resolve:DB_PORT)%'
                dbname:   '%env(resolve:DB_DBNAME)%'
                user:     '%env(resolve:DB_USER)%'
                password: '%env(resolve:DB_PASSWORD)%'
                charset:  '%env(resolve:DB_CHARSET)%'
                mapping_types:
                    tipo_velocidade: string
                    tipo_interface: string
                    tipo_transmissao: string
                    tipo_item_produto: string
                    tipo_grupo_produto: string
            cep:
                driver:   '%env(resolve:DB_DRIVER)%'
                host:     '%env(resolve:DB_HOST)%'
                port:     '%env(resolve:DB_PORT)%'
                dbname:   '%env(resolve:DB_DBNAME)%'
                user:     '%env(resolve:DB_USER)%'
                password: '%env(resolve:DB_PASSWORD)%'
                charset:  '%env(resolve:DB_CHARSET)%'
                schema_filter: '%env(resolve:DB_CEP_SCHEMA)%'
            financeiro:
                driver:   '%env(resolve:DB_FINANC_DRIVER)%'
                host:     '%env(resolve:DB_FINANC_HOST)%'
                port:     '%env(resolve:DB_FINANC_PORT)%'
                dbname:   '%env(resolve:DB_FINANC_DBNAME)%'
                user:     '%env(resolve:DB_FINANC_USER)%'
                password: '%env(resolve:DB_FINANC_PASSWORD)%'
                charset:  '%env(resolve:DB_FINANC_CHARSET)%'
                mapping_types:
                    enum: string
            gcdb:
                driver:   '%env(resolve:DB_GCDB_DRIVER)%'
                host:     '%env(resolve:DB_GCDB_HOST)%'
                port:     '%env(resolve:DB_GCDB_PORT)%'
                dbname:   '%env(resolve:DB_GCDB_DBNAME)%'
                user:     '%env(resolve:DB_GCDB_USER)%'
                password: '%env(resolve:DB_GCDB_PASSWORD)%'
                charset:  '%env(resolve:DB_GCDB_CHARSET)%'
                mapping_types:
                    enum: string
    orm:
        default_entity_manager: default
        auto_generate_proxy_classes: true
        entity_managers:
            default:
                connection: default
                mappings:
                    Cep:
                        is_bundle: false
                        type: yml
                        dir: '%kernel.project_dir%/config/doctrine/cep'
                        prefix: 'App\Entity'
                        alias: App\Entity
            cep:
                connection: cep
                mappings:
                    Cep:
                        is_bundle: false
                        type: yml
                        dir: '%kernel.project_dir%/config/doctrine/cep'
                        prefix: 'App\Entity'
                        alias: App\Entity
            financeiro:
                connection: financeiro
                mappings:
                    Financeiro:
                        is_bundle: false
                        type: yml
                        dir: '%kernel.project_dir%/config/doctrine/financeiro'
                        prefix: 'App\Entity'
                        alias: App\Entity
            gcdb:
                connection: gcdb
                mappings:
                    Gcdb:
                        is_bundle: false
                        type: yml
                        dir: '%kernel.project_dir%/config/doctrine/gcdb'
                        prefix: 'App\Entity'
                        alias: App\Entity
                        