parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver:   '%env(resolve:DB_DRIVER)%'
                host:     '%env(resolve:DB_HOST)%'
                port:     '%env(resolve:DB_PORT)%'
                dbname:   '%env(resolve:DB_DBNAME)%'
                user:     '%env(resolve:DB_USER)%'
                password: '%env(resolve:DB_PASSWORD)%'
                charset:  '%env(resolve:DB_CHARSET)%'
                server_version: 1
                mapping_types:
                    tipo_velocidade: string
                    tipo_interface: string
                    tipo_transmissao: string
                    tipo_item_produto: string
                    tipo_grupo_produto: string
            cep:
                driver:   '%env(resolve:DB_DRIVER)%'
                host:     '%env(resolve:DB_HOST)%'
                port:     '%env(resolve:DB_PORT)%'
                dbname:   '%env(resolve:DB_DBNAME)%'
                user:     '%env(resolve:DB_USER)%'
                password: '%env(resolve:DB_PASSWORD)%'
                server_version: 1
                charset:  '%env(resolve:DB_CHARSET)%'
                schema_filter: '%env(resolve:DB_CEP_SCHEMA)%'
            cobranca:
                driver:   '%env(resolve:DB_DRIVER)%'
                host:     '%env(resolve:DB_HOST)%'
                port:     '%env(resolve:DB_PORT)%'
                dbname:   '%env(resolve:DB_COBRANCA)%'
                user:     '%env(resolve:DB_USER)%'
                password: '%env(resolve:DB_PASSWORD)%'
                charset:  '%env(resolve:DB_CHARSET)%'
                server_version: 1
                mapping_types:
                    _int4: integer
            mysql:
                driver:   '%env(resolve:DB_MYSQL_DRIVER)%'
                host:     '%env(resolve:DB_MYSQL_HOST)%'
                port:     '%env(resolve:DB_MYSQL_PORT)%'
                dbname:   '%env(resolve:DB_MYSQL_DBNAME)%'
                user:     '%env(resolve:DB_MYSQL_USER)%'
                password: '%env(resolve:DB_MYSQL_PASSWORD)%'
                charset:  '%env(resolve:DB_MYSQL_CHARSET)%'
                server_version: 1
                mapping_types:
                    enum: string
            sqlserver_protheus:
                driver:   'sqlsrv'
                host:     '187.94.58.102'
                port:     '52731'
                dbname:   'NRS3VM'
                user:     'usr_NRS3VM_READ'
                password: 'GdZIxcJRlor3gGD'
                server_version: 1
    orm:
        default_entity_manager: default
        auto_generate_proxy_classes: true
        entity_managers:
            default:
                connection: default
                mappings:
                    Cep:
                        is_bundle: false
                        type: yml
                        dir: '%kernel.project_dir%/config/doctrine/cep'
                        prefix: 'App\Entity'
                        alias: AppEntity
            cep:
                connection: cep
                mappings:
                    Cep:
                        is_bundle: false
                        type: yml
                        dir: '%kernel.project_dir%/config/doctrine/cep'
                        prefix: 'App\Entity'
                        alias: AppEntity
            cobranca:
                connection: cobranca
                mappings:
                    Cep:
                        is_bundle: false
                        type: yml
                        dir: '%kernel.project_dir%/config/doctrine/postgres'
                        prefix: 'App\Entity'
                        alias: AppEntity
            mysql:
                connection: mysql
                mappings:
                    Mysql:
                        is_bundle: false
                        type: yml
                        dir: '%kernel.project_dir%/config/doctrine/mysql'
                        prefix: 'App\Entity'
                        alias: AppEntity
            sqlserver_protheus:
                connection: sqlserver_protheus
                mappings:
                    Mysql:
                        is_bundle: false
                        type: yml
                        dir: '%kernel.project_dir%/config/doctrine/sqlserver'
                        prefix: 'App\Entity'
                        alias: AppEntity

                        
