cep_search:
    path: /search/{cep}
    controller: 'App\Controller\Cep\CepController::searchCep'
    methods: [GET]
    defaults:
        _format: json
    requirements:
        cep: '\d+'
cep_create:
    path: /
    controller: 'App\Controller\Cep\CepController::createCep'
    methods: [POST]
    defaults:
        _format: json
        