App\Entity\Financeiro\EnderecoentregaatributovalorHisto:
    type: entity
    table: enderecoentregaatributovalor_histo
    indexes:
        fk_enderecoentregaatributovalor_histo_endeentratrivalo_codi_idx:
            columns:
                - endeentratrivalo_codigoid
    id:
        endeentratrivaloHisto:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: endeentratrivalo_histo
            generator:
                strategy: IDENTITY
    fields:
        atrivaloCodigoid:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: atrivalo_codigoid
        endeentratrivaloValor:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
            column: endeentratrivalo_valor
        endeentratrivaloDescricao:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
            column: endeentratrivalo_descricao
        dataInc:
            type: datetime
            nullable: true
            column: data_inc
        registrante:
            type: integer
            nullable: true
            options:
                unsigned: false
    manyToOne:
        endeentratrivaloCodigoid:
            targetEntity: App\Entity\Financeiro\Enderecoentregaatributovalor
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                endeentratrivalo_codigoid:
                    referencedColumnName: endeentratrivalo_codigoid
            orphanRemoval: false
    lifecycleCallbacks: {  }
