App\Entity\Financeiro\Envio:
    type: entity
    table: envio
    id:
        enviCodigoid:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: envi_codigoid
            generator:
                strategy: IDENTITY
    fields:
        enviNome:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: envi_nome
    lifecycleCallbacks: {  }
