App\Entity\Financeiro\Postagem:
    type: entity
    table: financeiro.postagem
    indexes:
        fk_postagem_fatura1_idx:
            columns:
                - fatu_codigoid
        fk_postagem_ar1_idx:
            columns:
                - ar_codigoid
    id:
        postCodigoid:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: post_codigoid
            generator:
                strategy: IDENTITY
    fields:
        usuaCodigoid:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: usua_codigoid
        postDatainc:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
            column: post_datainc
        postDatarecebimento:
            type: datetime
            nullable: true
            column: post_datarecebimento
    manyToOne:
        arCodigoid:
            targetEntity: App\Entity\Financeiro\Ar
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                ar_codigoid:
                    referencedColumnName: ar_codigoid
            orphanRemoval: false
        fatuCodigoid:
            targetEntity: App\Entity\Financeiro\Fatura
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                fatu_codigoid:
                    referencedColumnName: fatu_codigoid
            orphanRemoval: false
    lifecycleCallbacks: {  }
