App\Entity\Financeiro\Enderecoentrega:
    type: entity
    table: enderecoentrega
    indexes:
        idx_enderecoentrega_endeentr_id_index:
            columns:
                - endeentr_codigoid
        fk_endereco_contrato1_idx:
            columns:
                - cont_codigoid
        idx_apoio_consulta:
            columns:
                - endeentr_codigoid
                - endeentr_logradouro
                - endeentr_ponta
                - endeentr_numero
                - endeentr_bairro
                - endeentr_estado
                - endeentr_complemento
                - endeentr_pais
                - endeentr_cidade
    id:
        endeentrCodigoid:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: endeentr_codigoid
            generator:
                strategy: IDENTITY
    fields:
        contCodigoid:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: cont_codigoid
        endeentrConcentrador:
            type: boolean
            nullable: false
            column: endeentr_concentrador
        endeentrPais:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: endeentr_pais
        endeentrEstado:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: endeentr_estado
        endeentrCidade:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: endeentr_cidade
        endeentrBairro:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: endeentr_bairro
        endeentrLogradouro:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: endeentr_logradouro
        endeentrCep:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: endeentr_cep
        endeentrNumero:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: endeentr_numero
        endeentrComplemento:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: endeentr_complemento
        endeentrPonta:
            type: string
            nullable: true
            length: 10
            options:
                fixed: false
            column: endeentr_ponta
        endeentrLatitude:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: endeentr_latitude
        endeentrLongitude:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: endeentr_longitude
        endeentrDesignadorOld:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: endeentr_designador_old
        admLogradouro:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: adm_logradouro
    lifecycleCallbacks: {  }
