App\Entity\Financeiro\Status:
    type: entity
    table: financeiro.status
    id:
        statCodigoid:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: stat_codigoid
            generator:
                strategy: IDENTITY
    fields:
        statNome:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
            column: stat_nome
    lifecycleCallbacks: {  }
