App\Entity\Financeiro\Pagina:
    type: entity
    table: financeiro.pagina
    indexes:
        fk_pagina_pagina1_idx:
            columns:
                - pagi_proxima
        fk_pagina_documento1_idx:
            columns:
                - docu_codigoid
    id:
        pagiCodigoid:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: pagi_codigoid
            generator:
                strategy: IDENTITY
    fields:
        pagiPagina:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: pagi_pagina
        pagiNome:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: pagi_nome
        pagiExtensao:
            type: string
            nullable: false
            length: 5
            options:
                fixed: false
            column: pagi_extensao
        pagiDatainc:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
            column: pagi_datainc
        pagiTexto:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
            column: pagi_texto
    manyToOne:
        docuCodigoid:
            targetEntity: App\Entity\Financeiro\Documento
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                docu_codigoid:
                    referencedColumnName: docu_codigoid
            orphanRemoval: false
        pagiProxima:
            targetEntity: App\Entity\Financeiro\Pagina
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                pagi_proxima:
                    referencedColumnName: pagi_codigoid
            orphanRemoval: false
    lifecycleCallbacks: {  }
