App\Entity\Financeiro\ContratoAprovacaoFechamento:
    type: entity
    table: financeiro.contrato_aprovacao_fechamento
    id:
        idContrato:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_contrato
            generator:
                strategy: IDENTITY
    fields:
        active:
            type: boolean
            nullable: true
        aprovedBy:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: aproved_by
        chanceId:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: chance_id
        dateAproval:
            type: datetime
            nullable: true
            column: date_aproval
        dateClosed:
            type: datetime
            nullable: true
            column: date_closed
        dateRecord:
            type: datetime
            nullable: true
            column: date_record
        delta:
            type: float
            nullable: true
            precision: 10
            scale: 0
        description:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
        tag:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
        walletId:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: wallet_id
        classification:
            type: integer
            nullable: true
            options:
                unsigned: false
        vendaValeu:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: venda_valeu
        tipovenda:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: tipoVenda
    lifecycleCallbacks: {  }
