App\Entity\Financeiro\Bloqueio:
    type: entity
    table: bloqueio
    id:
        bloqCodigoid:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: bloq_codigoid
            generator:
                strategy: IDENTITY
    fields:
        bloqAcao:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
            column: bloq_acao
    lifecycleCallbacks: {  }
