App\Entity\Financeiro\Modelo:
    type: entity
    table: modelo
    indexes:
        fk_modelo_contrato1_idx:
            columns:
                - cont_codigoid
    id:
        modeCodigoid:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: mode_codigoid
            generator:
                strategy: IDENTITY
    fields:
        modeNome:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: mode_nome
        modeAtivo:
            type: boolean
            nullable: false
            column: mode_ativo
        modeDatainc:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
            column: mode_datainc
        modeDatafim:
            type: datetime
            nullable: true
            column: mode_datafim
    manyToOne:
        contCodigoid:
            targetEntity: App\Entity\Financeiro\Contrato
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                cont_codigoid:
                    referencedColumnName: cont_codigoid
            orphanRemoval: false
    lifecycleCallbacks: {  }
