App\Entity\Financeiro\Tipodocumento:
    type: entity
    table: tipodocumento
    id:
        tipodocuCodigoid:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: tipodocu_codigoid
            generator:
                strategy: IDENTITY
    fields:
        tipodocuNome:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: tipodocu_nome
    lifecycleCallbacks: {  }
