App\Entity\Financeiro\Aprovacao:
    type: entity
    table: aprovacao
    id:
        aproCodigoid:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: apro_codigoid
            generator:
                strategy: IDENTITY
    fields:
        aproNome:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
            column: apro_nome
        aproTipo:
            type: integer
            nullable: false
            options:
                unsigned: false
                comment: "apro_tipo: tipo de aprovação Interna = 1\n                  tipo de aprovação Externa = 2\n                  tipo de aprovação da ativação = 3"
            column: apro_tipo
    lifecycleCallbacks: {  }
