App\Entity\Financeiro\TmpLogCliente:
    type: entity
    table: financeiro.tmp_log_cliente
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        descricao:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
        dataInc:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
            column: data_inc
        cnpj:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
    lifecycleCallbacks: {  }
