App\Entity\Financeiro\Rangear:
    type: entity
    table: financeiro.rangear
    id:
        rangarCodigoid:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: rangar_codigoid
            generator:
                strategy: IDENTITY
    fields:
        rangarDatainc:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
            column: rangar_datainc
        rangarInicio:
            type: string
            nullable: false
            length: 10
            options:
                fixed: false
            column: rangar_inicio
        rangarFim:
            type: string
            nullable: false
            length: 10
            options:
                fixed: false
            column: rangar_fim
        rangarAtivo:
            type: boolean
            nullable: false
            column: rangar_ativo
        rangearSerie:
            type: string
            nullable: false
            length: 2
            options:
                fixed: false
            column: rangear_serie
    lifecycleCallbacks: {  }
