App\Entity\Financeiro\Contratoproposta:
    type: entity
    table: financeiro.contratoproposta
    indexes:
        idx_idcontrato:
            columns:
                - idcontrato
        idx_idproposta:
            columns:
                - idproposal
    uniqueConstraints:
        idcontrato_proposta_UNIQUE:
            columns:
                - id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        idproposal:
            type: integer
            nullable: false
            options:
                unsigned: false
        idcontrato:
            type: integer
            nullable: false
            options:
                unsigned: false
    lifecycleCallbacks: {  }
