App\Entity\Financeiro\Tipologging:
    type: entity
    table: financeiro.tipologging
    id:
        tipologgCodigoid:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: tipologg_codigoid
            generator:
                strategy: IDENTITY
    fields:
        tipologgNome:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
            column: tipologg_nome
    lifecycleCallbacks: {  }
