App\Entity\Financeiro\ServicosWanServicoAgregado:
    type: entity
    table: financeiro.servicos_wan_servico_agregado
    indexes:
        servagre_codigoid:
            columns:
                - servagre_codigoid
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        tprIdServico:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: tpr_id_servico
        dataInc:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
            column: data_inc
    manyToOne:
        servagreCodigoid:
            targetEntity: App\Entity\Financeiro\ServicoAgregado
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                servagre_codigoid:
                    referencedColumnName: servagre_codigoid
            orphanRemoval: false
    lifecycleCallbacks: {  }
