App\Entity\Gcdb\AdmTipoComplemento:
    type: entity
    table: gcdb.adm_tipo_complemento
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nome:
            type: string
            nullable: true
            length: 30
            options:
                fixed: false
        sigla:
            type: string
            nullable: true
            length: 4
            options:
                fixed: true
    lifecycleCallbacks: {  }
