App\Entity\Gcdb\CadUsersSegmento:
    type: entity
    table: gcdb.cad_users_segmento
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        descricao:
            type: string
            nullable: false
            length: 90
            options:
                fixed: false
    lifecycleCallbacks: {  }
