App\Entity\Luma\Poprelacaolocalizacao:
    type: entity
    table: luma.poprelacaolocalizacao
    indexes:
        id_tipo:
            columns:
                - id_tipo
        id_pop:
            columns:
                - id_pop
        id_localizacao:
            columns:
                - id_localizacao
    id:
        idPopLocalizacao:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_pop_localizacao
            generator:
                strategy: IDENTITY
    fields:
        dataInicio:
            type: datetime
            nullable: true
            column: data_inicio
        dataFim:
            type: datetime
            nullable: true
            column: data_fim
        usuario:
            type: string
            nullable: true
            length: 80
            options:
                fixed: false
            column: Usuario
        usuarioAprovador:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: usuario_aprovador
        observacaoAprovador:
            type: string
            nullable: true
            length: 500
            options:
                fixed: false
            column: observacao_aprovador
        dataAprovador:
            type: datetime
            nullable: true
            column: data_aprovador
    manyToOne:
        pop:
            targetEntity: App\Entity\Luma\Pop
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_pop:
                    referencedColumnName: id_pop
            orphanRemoval: false
        poplocalizacao:
            targetEntity: Poplocalizacao
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_localizacao:
                    referencedColumnName: id_localizacao
            orphanRemoval: false
        poptipolocalizacao:
            targetEntity: App\Entity\Luma\Poptipolocalizacao
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_tipo:
                    referencedColumnName: id_tipo
            orphanRemoval: false
    lifecycleCallbacks: {  }
