App\Entity\Luma\Poplocalizacao:
    type: entity
    table: luma.poplocalizacao
    id:
        idLocalizacao:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_localizacao
            generator:
                strategy: IDENTITY
    fields:
        cidade:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
        endereco:
            type: string
            nullable: true
            length: 200
            options:
                fixed: false
        bairro:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
        referencia:
            type: string
            nullable: true
            length: 500
            options:
                fixed: false
        latitude:
            type: string
            nullable: true
            length: 20
            options:
                fixed: false
        longitude:
            type: string
            nullable: true
            length: 20
            options:
                fixed: false
        latitudeMaps:
            type: string
            nullable: true
            length: 20
            options:
                fixed: false
            column: latitude_maps
        longitudeMaps:
            type: string
            nullable: true
            length: 20
            options:
                fixed: false
            column: longitude_maps
        telefone1:
            type: string
            nullable: true
            length: 20
            options:
                fixed: false
        telefone2:
            type: string
            nullable: true
            length: 20
            options:
                fixed: false
        cep:
            type: string
            nullable: true
            length: 15
            options:
                fixed: false
        uf:
            type: string
            nullable: true
            length: 200
            options:
                fixed: false
        nome:
            type: string
            nullable: true
            length: 200
            options:
                fixed: false
        numero:
            type: integer
            nullable: true
            options:
                unsigned: false
        complemento:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
        complementoNumero:
            type: string
            nullable: true
            length: 15
            options:
                fixed: false
            column: complemento_numero
        localeCodigoid:
            type: integer
            nullable: true
            options:
                unsigned: false
                comment: 'Billing.locale '
            column: locale_codigoid
    lifecycleCallbacks: {  }
