App\Entity\Cobranca\InvoiceInformationLog:
    type: entity
    table: invoice_information_log
    id:
        idInvoiceInformationLog:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_invoice_information_log
            generator:
                strategy: SEQUENCE
    fields:
        cnpj:
            type: string
            nullable: true
            length: 14
            options:
                fixed: false
        idFilial:
            type: string
            nullable: true
            length: 2
            options:
                fixed: false
            column: id_filial
        status:
            type: string
            nullable: true
            length: 1
            options:
                fixed: true
        codigoPedidoProtheus:
            type: string
            nullable: true
            length: 6
            options:
                fixed: false
            column: codigo_pedido_protheus
        codigoPedido:
            type: string
            nullable: true
            length: 20
            options:
                fixed: false
            column: codigo_pedido
        cgcCliente:
            type: string
            nullable: true
            length: 14
            options:
                fixed: false
            column: cgc_cliente
        invoiceSerie:
            type: string
            nullable: true
            length: 3
            options:
                fixed: false
            column: invoice_serie
        invoiceNumero:
            type: string
            nullable: true
            length: 9
            options:
                fixed: false
            column: invoice_numero
        invoiceEmissao:
            type: date
            nullable: true
            column: invoice_emissao
        codigoProduto:
            type: string
            nullable: true
            length: 15
            options:
                fixed: false
            column: codigo_produto
        total:
            type: decimal
            nullable: true
            precision: 17
            scale: 2
        cfopOperacao:
            type: decimal
            nullable: true
            precision: 4
            scale: 0
            column: cfop_operacao
        dataInc:
            type: datetime
            nullable: false
            column: data_inc
        nomearquivo:
            type: text
            nullable: false
            length: null
            options:
                fixed: false
    manyToOne:
        invoice:
            targetEntity: App\Entity\Cobranca\Invoice
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: invoiceInformationLog
            joinColumns:
                codigo_pedido:
                    referencedColumnName: id_invoice
            orphanRemoval: false
    lifecycleCallbacks: {  }
