App\Entity\Cobranca\Banco:
    type: entity
    table: banco
    indexes:
        index_cobrador_banco:
            columns:
                - cobr_codigoid
        index_banco_banc_codigoid:
            columns:
                - banc_codigoid
    id:
        bancCodigoid:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: banc_codigoid
            generator:
                strategy: SEQUENCE
    fields:
        banco:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
        agencia:
            type: string
            nullable: false
            length: 10
            options:
                fixed: false
        conta:
            type: string
            nullable: false
            length: 30
            options:
                fixed: false
        bancoNum:
            type: string
            nullable: false
            length: 3
            options:
                fixed: true
            column: banco_num
        default:
            type: boolean
            nullable: true
            options:
                comment: ' '
        boleto:
            type: boolean
            nullable: true
    manyToOne:
        cobrador:
            targetEntity: App\Entity\Cobranca\Cobrador
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                cobr_codigoid:
                    referencedColumnName: cobr_codigoid
            orphanRemoval: false
    lifecycleCallbacks: {  }
