App\Entity\Cobranca\Cobrador:
    type: entity
    table: cobrador
    id:
        cobrCodigoid:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: cobr_codigoid
            generator:
                strategy: SEQUENCE
    fields:
        razaoSocial:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
            column: razao_social
        cnpj:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
        endereco:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
        numero:
            type: string
            nullable: true
            length: 15
            options:
                fixed: false
        complemento:
            type: string
            nullable: true
            length: 80
            options:
                fixed: false
        bairro:
            type: string
            nullable: true
            length: 80
            options:
                fixed: false
        cidade:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
        estado:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
        pais:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
        ie:
            type: string
            nullable: true
            length: 14
            options:
                fixed: false
        telefone:
            type: string
            nullable: true
            length: 15
            options:
                fixed: false
        fax:
            type: string
            nullable: true
            length: 15
            options:
                fixed: false
        cadUsersId:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: cad_users_id
    lifecycleCallbacks: {  }
