App\Entity\Cobranca\Cc:
    type: entity
    table: cc
    indexes:
        index_cc_banc_codigoid:
            columns:
                - banc_codigoid
        cc_cc_codigoid_idx:
            columns:
                - cc_codigoid
        index_cc_customer:
            columns:
                - customer
        index_cc_oper_codigoid:
            columns:
                - oper_codigoid
    id:
        ccCodigoid:
            type: bigint
            nullable: false
            options:
                unsigned: false
            id: true
            column: cc_codigoid
            generator:
                strategy: SEQUENCE
    fields:
        customer:
            type: bigint
            nullable: false
            options:
                unsigned: false
        dataInc:
            type: datetime
            nullable: false
            column: data_inc
        valor:
            type: decimal
            nullable: false
            precision: 10
            scale: 2
        tipo:
            type: string
            nullable: false
            length: 1
            options:
                fixed: true
        descricao:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        saldoAnterior:
            type: decimal
            nullable: false
            precision: 10
            scale: 2
            column: saldo_anterior
        idUser:
            type: bigint
            nullable: true
            options:
                unsigned: false
            column: id_user
        dataRegistroSistema:
            type: date
            nullable: true
            options:
                default: now()
            column: data_registro_sistema
    manyToOne:
        banco:
            targetEntity: App\Entity\Cobranca\Banco
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                banc_codigoid:
                    referencedColumnName: banc_codigoid
            orphanRemoval: false
        ccOperacao:
            targetEntity: App\Entity\Cobranca\CcOperacao
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                oper_codigoid:
                    referencedColumnName: oper_codigoid
            orphanRemoval: false
    manyToMany:
        boleto:
            targetEntity: App\Entity\Cobranca\Boleto
            cascade: {  }
            fetch: LAZY
            mappedBy: cc
            inversedBy: null
            joinTable: null
            orderBy: null
        invoice:
            targetEntity: App\Entity\Cobranca\Invoice
            cascade: {  }
            fetch: LAZY
            mappedBy: cc
            inversedBy: null
            joinTable: null
            orderBy: null
    lifecycleCallbacks: {  }
