App\Entity\Cobranca\BoletoPagador:
    type: entity
    table: boleto_pagador
    indexes:
        index_boleto_pagador:
            columns:
                - id_boleto_pagador
        index_boleto_pagador_customer:
            columns:
                - cnpj
    id:
        idBoletoPagador:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_boleto_pagador
            generator:
                strategy: SEQUENCE
    fields:
        razaoSocial:
            type: string
            nullable: true
            length: 80
            options:
                fixed: false
            column: razao_social
        cnpj:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
        endereco:
            type: string
            nullable: true
            length: 80
            options:
                fixed: false
        numero:
            type: string
            nullable: true
            length: 15
            options:
                fixed: false
        complemento:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
        bairro:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
        cidade:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
        estado:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
        pais:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
        cep:
            type: string
            nullable: true
            length: 8
            options:
                fixed: true
    lifecycleCallbacks: {  }
