App\Entity\Cobranca\CobrancaHistoricoStatus:
    type: entity
    table: cobranca_historico_status
    indexes:
        index1:
            columns:
                - id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        status:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
    lifecycleCallbacks: {  }
