App\Entity\Gcdb\AdmLogradouro:
    type: entity
    table: gcdb.adm_logradouro
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nome:
            type: string
            nullable: true
            length: 30
            options:
                fixed: false
    lifecycleCallbacks: {  }
