App\Entity\Gcdb\AdmTipoNome:
    type: entity
    table: gcdb.adm_tipo_nome
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nome:
            type: string
            nullable: true
            length: 20
            options:
                fixed: false
        tipo:
            type: string
            nullable: true
            length: 0
            options:
                fixed: false
    lifecycleCallbacks: {  }
