monolog:
    channels: ['salesforce']
    handlers:
        salesforce:
            level:    debug
            type:     stream
            path:     '%kernel.logs_dir%/%kernel.environment%.salesforce.log'
            channels: [salesforce]
        protheus:
            level:    debug
            type:     stream
            path:     '%kernel.logs_dir%/%kernel.environment%.protheus.log'
            channels: [protheus]
        main:
            type: fingers_crossed
            action_level: error
            handler: nested
            excluded_404s:
                # regex: exclude all 404 errors from the logs
                - ^/
        nested:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!salesforce", "!protheus"]
        deprecation:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.deprecations.log"
        deprecation_filter:
            type: filter
            handler: deprecation
            max_level: info
            channels: ["php"]
