#index:
#    path: /
#    controller: App\Controller\DefaultController::index
cep:
    prefix: /cep
    resource: './routes/cep.yaml'
geolocation:
    prefix: /geo
    resource: './routes/geo.yaml'
pedido:
    prefix: /pedido
    resource: './routes/pedido.yaml'
cliente:
    prefix: /cliente
    resource: './routes/cliente.yaml'