App\Entity\Cep\LogGrandeUsuario:
    type: entity
    table: cep.log_grande_usuario
    indexes:
        IDX_6F576119E4B361A6:
            columns:
                - loc_nu_sequencial
        IDX_6F5761196ECF04C5:
            columns:
                - log_nu_sequencial
        IDX_6F576119E21A128D:
            columns:
                - bai_nu_sequencial
    id:
        gruNuSequencial:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: gru_nu_sequencial
            generator:
                strategy: SEQUENCE
    fields:
        ufeSg:
            type: string
            nullable: false
            length: 2
            options:
                fixed: false
            column: ufe_sg
        gruNo:
            type: string
            nullable: false
            length: 96
            options:
                fixed: false
            column: gru_no
        cep:
            type: string
            nullable: false
            length: 16
            options:
                fixed: false
        gruEndereco:
            type: string
            nullable: false
            length: 200
            options:
                fixed: false
            column: gru_endereco
        temp:
            type: string
            nullable: true
            length: 8
            options:
                fixed: true
    manyToOne:
        logLocalidade:
            targetEntity: App\Entity\Cep\LogLocalidade
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: logGrandeUsuario
            joinColumns:
                loc_nu_sequencial:
                    referencedColumnName: loc_nu_sequencial
            orphanRemoval: false
        logLogradouro:
            targetEntity: App\Entity\Cep\LogLogradouro
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: logGrandeUsuario
            joinColumns:
                log_nu_sequencial:
                    referencedColumnName: log_nu_sequencial
            orphanRemoval: false
        logBairro:
            targetEntity: App\Entity\Cep\LogBairro
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: logGrandeUsuario
            joinColumns:
                bai_nu_sequencial:
                    referencedColumnName: bai_nu_sequencial
            orphanRemoval: false
    lifecycleCallbacks: {  }
